---
- name: Create required MySQL directories
  file:
    path: "{{ item.path }}"
    state: directory
    mode: '0755'
  with_items:
    - { path: '/u101/mysql/data' }
    - { path: '/u101/mysql/data/log' }
    - { path: '/u101/mysql/data/database' }
    - { path: '/u102/mysql/archive' }
    - { path: '/u102/mysql/archive/binlog' }
    - { path: '/u103/mysql/backup' }